# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86_64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86_64)
  EX1_config = debug_x86_64
  TP_config = debug_x86_64
  spdlog_config = debug_x86_64

else ifeq ($(config),debug_x86)
  EX1_config = debug_x86
  TP_config = debug_x86
  spdlog_config = debug_x86

else ifeq ($(config),release_x86_64)
  EX1_config = release_x86_64
  TP_config = release_x86_64
  spdlog_config = release_x86_64

else ifeq ($(config),release_x86)
  EX1_config = release_x86
  TP_config = release_x86
  spdlog_config = release_x86

else ifeq ($(config),dist_x86_64)
  EX1_config = dist_x86_64
  TP_config = dist_x86_64
  spdlog_config = dist_x86_64

else ifeq ($(config),dist_x86)
  EX1_config = dist_x86
  TP_config = dist_x86
  spdlog_config = dist_x86

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := EX1 TP spdlog

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: spdlog

EX1:
ifneq (,$(EX1_config))
	@echo "==== Building EX1 ($(EX1_config)) ===="
	@${MAKE} --no-print-directory -C EX/EX1 -f Makefile config=$(EX1_config)
endif

TP: spdlog
ifneq (,$(TP_config))
	@echo "==== Building TP ($(TP_config)) ===="
	@${MAKE} --no-print-directory -C . -f TP.make config=$(TP_config)
endif

spdlog:
ifneq (,$(spdlog_config))
	@echo "==== Building spdlog ($(spdlog_config)) ===="
	@${MAKE} --no-print-directory -C Vendor/spdlog -f Makefile config=$(spdlog_config)
endif

clean:
	@${MAKE} --no-print-directory -C EX/EX1 -f Makefile clean
	@${MAKE} --no-print-directory -C . -f TP.make clean
	@${MAKE} --no-print-directory -C Vendor/spdlog -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86_64"
	@echo "  debug_x86"
	@echo "  release_x86_64"
	@echo "  release_x86"
	@echo "  dist_x86_64"
	@echo "  dist_x86"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   EX1"
	@echo "   TP"
	@echo "   spdlog"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"